import React from 'react';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { TrendingDown, Globe, Activity, CircleX } from 'lucide-react';

const dataPieC = [
  { name: 'Nicho Analógico (Profesionales/Puristas)', value: 12 },
  { name: 'Colapso de Mercado - Migración a Mobile IA', value: 88 }
];
const COLORS = ['#111827', '#A51C30'];

export const caso3 = {
  id: "case-3",
  title: "Caso 3: Costos Hundidos y Tragedia Disruptiva en 'Luminar Dynamics'",
  content: (
    <div className="space-y-8 font-serif leading-relaxed text-lg text-gray-800">
      
      {/* Abstracto Ejecutivo */}
      <div className="bg-[#111827] text-white p-6 rounded shadow-lg border-l-4 border-[#D4AF37]">
        <h3 className="text-[#D4AF37] font-bold text-2xl mb-4 tracking-wide font-sans uppercase">Abstracto Ejecutivo</h3>
        <p className="mb-4 text-gray-300">
          Luminar Dynamics, el monarca casi centenario y aristocrático de la óptica de precisión fotográfica (cámaras DSLR puras de espejos físicos), sucumbió a un derrumbe apocalíptico del 88% de su mercado masivo en apenas 60 meses. Su balance inicial de la Matriz EFI era abrumador: patentes de cristal óptico insuperables, y un "brand equity" mundial que equivalía a calidad artesanal sinónima de lujo fotográfico profesional sin fisuras aparentes.
        </p>
        <p className="mb-4 text-gray-300">
          Sin embargo, la cúpula ejecutiva padecía una miopía cognitiva crónica bajo el esquema PESTEL y Porter. Desestimaron con soberbia la irrupción del factor de convergencia tecnológica dictaminado por los chips telefónicos (IA + sensores lógicos digitales miniatura).
        </p>
        <p className="text-[#D4AF37] font-bold">
          Atrapados en una maraña monumental de gigantescos Costos Hundidos y Barreras de Salida letales, produjeron el cierre más triste del corporativismo reciente: una compañía que murió asfixiada financieramente mientras fabricaba sin cesar el producto más impecable y perfecto de un mundo paralelo que la sociedad ya no necesitaba, devorados por la "Dilema del Innovador" y el software implacable de bolsillo.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* PESTEL y Porter */}
        <div className="bg-gray-50 p-6 rounded-lg shadow-sm border border-gray-200">
          <h4 className="border-b border-[#D4AF37] pb-2 mb-4 flex items-center text-[#A51C30] font-bold tracking-wide font-sans text-xl">
            <Globe className="mr-2" size={24}/> La Ceguera Computacional (PESTEL)
          </h4>
          <p className="mb-4">
            Dentro de <strong>PESTEL</strong>, dos fallas tectónicas ignoradas destruyeron su mercado: Un shift contundente <strong>Socio-Cultural</strong> (el humano masivo ya no deseaba preservar recuerdos con calidad óptica museo, ansiaba inmediatez comunicativa validada socialmente instantáneamente en redes como Instagram) y el colosal maremoto <strong>Tecnológico</strong> (Fotografía Computacional inyectada de NPU y machine learning).
          </p>
          <p>
            Al correr la mirada a la Estrategia de <strong>Porter</strong>, la devastación provino del factor más absoluto: La <em>Amenaza de Sustitutos Múltiples Perfectos y Rampantes</em>. Los teléfonos inteligentes no mejoraron a la cámara analógica ni deseaban competir en estatus, sencillamente la volvieron ridículamente irrelevante para el usuario de pasillo casual cotidiano de modo absoluto y definitorio destructivo.
          </p>
        </div>

        {/* Gráfico Financiero de Colapso */}
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 flex flex-col justify-center">
          <h4 className="border-b border-[#D4AF37] pb-2 mb-4 flex items-center text-[#A51C30] font-bold tracking-wide font-sans text-xl">
            <Activity className="mr-2" size={24}/> Evaporación Transaccional
          </h4>
          <div className="w-full">
            <ResponsiveContainer width="100%" height={260}>
              <PieChart>
                <Pie data={dataPieC} cx="50%" cy="50%" innerRadius={60} outerRadius={85} paddingAngle={2} dataKey="value" label={({name, percent}) => `${(percent * 100).toFixed(0)}%`}>
                  {dataPieC.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}
                </Pie>
                <Tooltip wrapperClassName="font-sans text-sm shadow-sm" formatter={(value) => [`${value}% del Mercado Base Histórico`]}/>
                <Legend iconType="circle" wrapperStyle={{fontSize: '14px', fontFamily: 'sans-serif', paddingTop: '20px'}}/>
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Barreras de Salida y Dilema del Innovador */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
        <div className="bg-gray-50 p-6 rounded-lg shadow-sm border border-gray-200">
           <h4 className="border-b border-[#D4AF37] pb-2 mb-6 flex items-center text-[#A51C30] font-bold tracking-wide font-sans text-xl">
            <CircleX className="mr-3" size={24}/> La Trampa de las Barreras de Salida
          </h4>
          <p className="mb-4">
            Al percibir el apocalipsis final cercano a sus umbrales operativos de quiebre, el intento por pivotar urgentemente chocó con fieras <strong>Barreras de Salida</strong> clásicas de un entorno manufacturero. Reclutaron penalidades pensionales, indemnizaciones de maquinarias inyectadas estáticas gigantescas desfasadas no transformables en masa a micro sensores.
          </p>
          <p>
            Esto significa financieramente letalmente grave: Resultaba infinitamente más caro liquidar las unidades desfasadas pasivas en bancarrota por leyes estrictas europeas que mantenerlas abiertas artificialmente sufriendo hemorragias de pérdidas puras directas (Cash Burning extremo masivo desangrante constante diario crónico persistente).
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
           <h4 className="border-b border-[#D4AF37] pb-2 mb-6 flex items-center text-[#A51C30] font-bold tracking-wide font-sans text-xl">
            <TrendingDown className="mr-3" size={24}/> El Dilema del Gran Innovador
          </h4>
          <p className="mb-4">
            Luminar experimentó de carne y hueso la teoría base de Harvard (El Dilema del Innovador clásico). Sus directivos despreciaron abiertamente las primeras cámaras móviles tildándolas de "juguetes ridículamente ruidosos y mediocres pixelados sin arte nativo ni sensibilidad lumínica ISO".
          </p>
          <p>
             Eran juguetes mediocres, pero lo suficientemente útiles para desplazar drásticamente a Luminar ante la avasallante y extrema conveniencia, superando ampliamente la racha de mejora de chip anual y robando al final al fotógrafo también profesional. Murió puliendo oro en la era instantánea y del cuarzo.
          </p>
        </div>
      </div>

      {/* Cita final de impacto */}
      <div className="mt-8 p-8 shadow border-l-8 border-[#A51C30] bg-[#A51C30]/5 font-serif italic text-[#111827] relative overflow-hidden">
        <div className="absolute top-4 right-4 text-[#A51C30] opacity-10 transform scale-150 origin-top-right">
          <TrendingDown size={120}/>
        </div>
        <p className="text-2xl leading-relaxed relative z-10 font-bold">
          "Luminar Dynamics sucumbió agonizando lentamente y en total negación asfixiante, siendo trágica, arrogante pero operativamente perfecta a niveles ridículos. Esculpieron artesanal y devotamente con el amor meticuloso de cien directores ciegos un producto milagroso óptico y exquisito, que simplemente las crueles leyes mundiales dictaminadas del algoritmo y del bolsillo desplazaron a la obsolescencia. Fabricar la armadura más resistente de toda la historia es un chiste brutal de la ironía temporal en la plena guerra universal moderna de pólvora encendida de chips rápidos de procesamiento neuronal y NPU ágiles infinitos del instante y la conectividad permanente conectiva incesante sin fin."
        </p>
        <p className="mt-6 font-sans font-bold text-sm text-[#A51C30] uppercase tracking-wider relative z-10 block">
          — Bitácora final de Liquidación de Activos de la firma Consultora Global Restructuring.
        </p>
      </div>
    </div>
  ),
  questions: [
    { q: "La falla cognitiva de Luminar al enfocarse en 'Mejorar lentes físicos pesados' en lugar de visualizar 'Cómo captura el humano moderno un breve recuerdo casual rápido', es un claro error estudiado por Harvard clásico como:", options: ["Falla en control logístico Lean (Kanban estricto equivocado) en matriz oriental", "Liderazgo irresponsable sin auditoría fiscal trimestral clara", "Miopía del Marketing Institucional / Miopía Estratégica ciega corporativa histórica de modelo", "Apalancamiento de sinergia de riesgo dual M&A adverso temprano inverso"], a: 2 },
    { q: "En la lectura pura estructural de las 5 Fuerzas de Porter, la gran avalancha de los teléfonos inteligentes se codifica inexcusablemente de forma absoluta directa como una:", options: ["Subida alocada paralizante y severa drástica brutal de todo el Poder Negociador inminente de Proveedor de materia plástica pura escasa mundial asiática tradicional paralizada en cuellos de botella", "Apertura enorme, profunda, letal y avasallante gigantesca aplastante e incesante de la temible Amenaza de Sustitutos y redefinición absoluta masiva del cuadrante de competencia frontal directa tecnológica funcional de uso perenne final nativo móvil de Silicon Valley nativa radical e inexorable de raíz y en amplitud masiva pura", "Baja drástica de las temibles amenazas de nuevos operarios", "Rebelión pasiva de recursos"], a: 1 },
    { q: "En un escenario crítico pesimista contable legal doloroso, las altas indemnizaciones pensionales laborales y pasivos ambientales rigurosos que paralizan liquidar corporaciones obsoletas se clasifican analíticamente crudo en estrategia industrial corporativa como:", options: ["Rendimiento marginal a futuro de bonos verdes estatales europeos subvencionados", "Fortalezas Menores orgánicas tácticas de alto rango de retención de recurso de personal fijo estático legal inamovible permanente", "Subsidios operacionales fiscales de amortización doble por abandono perenne", "Barreras de Salida letales, haciendo más caro cerrar la fábrica vieja paralela obsoleta que dejarla agonizando sangrando efectivo vital día a día produciendo meramente un exceso de inventario invendible ilíquido muerto perenne"], a: 3 },
    { q: "Si estructuramos audazmente y sin sesgos emocionales la Matriz EFI interna post disrupción inicial obvia de la firma luminar, el atributo de ser un 'Artesano de pulido mecánico analógico puro y meticuloso y estático y perfeccionista físico puro' debió imperativamente re-calificarse urgentemente dictatorialmente como:", options: ["Pilar Estratégico Mayor y central sostenedor indiscutido de supervivencia vital monopólica de facto B2C global tradicional inamovible eterno para la cúpula", "Debilidad Estructural de Rigidez (Inflexibilidad Operativa gigante monstruosa ante disrupción externa ágil minuciosa de chip pequeño) asignada imperativamente con el puntaje más bajo punitivo destructor disponible doloroso realista crudo frío", "Fortaleza Menor de base legal firme sólida y duradera en mercados en vías de claro y notable avance económico asiático de nichos alternos", "Valor inescrutable pasivo incalculable fiscal amortizable eternamente al alza garantizada B2B"], a: 1 },
    { q: "La firma cayó abatida e incinerada plenamente por el 'Dilema del Innovador clásico de Sillicon Valley', que reza categóricamente dogmáticamente e implacablemente comprobado históricamente que la tecnología móvil entrante competidora...", options: ["Eran monstruosamente caras absurdamente premium exclusivas limitadas B2B", "Copiaron legal y maliciosamente los planos CAD del modelo base principal original mecánico de obturadores de bronce aleaciones suizas idénticos 1:1 en fábricas de plástico para arruinar con total deliberado e intencional dumping asiático", "Irrumpió primero como un producto simple, marginal, defectuoso ópticamente comparado al rey del sector, pero era abrumadoramente superlativo en 'Conveniencia Portátil Universal y conectividad hiperactiva instantánea', escalando exponencialmente a devorar el espectro 'Suficientemente Bueno' matándolos por la base ignorada del mercado bajo masivo rápido", "Carecían inmensamente de chips o sensores e imprimen fotos polaroid instantáneas masivas sin química"], a: 2 },
    { q: "Al auditar con frialdad forense la degradación fatal del cuadrante VRIO de marca, el aclamado 'Brand Equity Lujoso Histórico Cien Años' de la mítica marca japonesa no sirvió de paraguas protector antiniebla inexpugnable, porque falló de base elemental crucial central sistémica vital trágica en su atributo de:", options: ["Raro (R) (Perdió la rareza porque el cuarzo es raro en bruto)", "Organización puramente publicitaria sindical gremial", "Inimitabilidad al 100% de los plásticos de moldes asiáticos inyectables sin matrices en corto plazo y con tirajes bajísimos sin escala B2C B2B conjunta híbrida general simple media", "Valor (V), porque una marca mítica y exclusiva ligada de raíz vital irremediable forzosamente e indisolublemente y en concreto total a un soporte puramente físico estático inerte e incomunicado pasivo analógico retro antiguo pesado muerto y doloroso de procesar en pc pierde dolorosamente con rapidez fugaz estrepitosa su percepción y dictamen central de valor intrínseco práctico para el vertiginoso frenético consumidor moderno líquido B2C ágil global general."], a: 3 },
    { q: "Desgranando retrospectivamente con furia metódica el macro análisis general generalista de su PESTEL inyectado exógenamente y destructor pasivo mortal, el clavo inicial central y fáctico de la debacle estrepitosa y pérdida masiva universal de la torta porcentual del mercado brutal de 60 meses referenciada a 88% es ineludiblemente encasillada como fuerza matriz en el espectro:", options: ["Político Aduanero Arancelario masivo unilateral dictatorial restrictivo de cupos fijos rígidos obligados ciegos", "Ecológico Medioambiental (Leyes verdes protecciones de químicos contaminantes residuales de película en Europa del este y de sur américa pasiva)", "Sociocultural / Tecnológico enlazado cruzado hibridado masivo (Democracia compulsiva total y definitiva de la fotografía IA hiper-escalable para el hambre insaciable y voraz perenne frenética validatoria constante del narcisismo puro en redes sociales de interconexión móvil masiva planetaria veloz al segundo de captura de forma efímera brutal impulsiva diaria gigante y universal del hombre moderno hiper-conectado dependiente ansioso impaciente estresado)", "Legal de marcas obsoletas perdidas pasadas en pleitos de la corte penal y constitucional de japón tradicional sin ley ni estado protector ágil global central."], a: 2 },
    { q: "Para haber tenido remota chance escueta de un 'Hard Turnaround' (Giro brutal y dramático y salvaje y visceral directivo salvífico), los banqueros exigen 'Amputar Activos ciegamente con un dolor masivo y sangría contable brutal y fría y agresiva y desgarradora de balance'. Conceptualmente esta técnica cruda y audaz en economía directiva general se encasilla categóricamente como:", options: ["Ignorar las Pérdidas Operacionales Netas asumiéndolas estáticas en un libro auxiliar y reevaluar la misión pasiva general con marketing publicitario intenso", "Asumir la pérdida irreversible trágica inyectada reconociendo el peso muerto enorme y absoluto implacable total de todos los Costos Hundidos fijos, desinvertir cerrando toda la operación fábrica tóxica y redirigir agresivamente frenéticamente heroicamente ese poco capital remanente líquido residual vivo corto oxigenado puro vital hacia un Nicho Extremo donde el móvil no los abata fácilmente y sea refugio protegido temporal e inelástico y caro B2B", "Liderazgo y Paridad de Costos inyectando inmensos pasivos hipotecarios a tasa muy variable local de moneda blanda en asía buscando precios baratos y pésima calidad extrema de volumen de relleno", "Pedir auxilio contable financiero al holding y aliar y hacer joint venture con la competencia analógica débil muerta zombi también y armar monopolio oligopólico pasivo fallido inútil ciego retro"], a: 1 },
    { q: "Identificando la migaja estructural operativa remanente tras la explosión y el tsunami, la única y estricta y radical y brutalmente disciplinada 'Estrategia Genérica' dictada como mandamiento inquebrantable para sostenerse oxigenado marginalmente en paz temporal es encasillar imperativamente al resto del cuerpo del 12% estricto con sangre remanente en:", options: ["Ser el indiscutido Dictador y General Máximo de liderazgo feroz y abrumador e indiscutible gigante universal asimétrico puro en costos hundidos compitiendo inútilmente y sangrando frontal, suicida e irracional ciegamente y estoica inútilmente contra la matriz oriental productora de los teléfonos celulares genéricos masivos mundiales de trillones americanos plásticos de silicio baratos producidos de a montones por segundo celeremente en serie", "Pivotar agresivamente fugazmente velozmente y en silencio cauteloso de trinchera estrecha escondido B2B B2C exclusivo ciegamente disciplinado hacia la Diferenciación Extrema Profunda Singular, Alta, pura de la pureza enfocada ineludiblemente encauzada en el Enfoque Racional y Fino de Nicho minucioso microscópico inelástico Premium Inabordable Especial elitista de artesanos de ultra élite exclusivo y selectivo caro carísimo para nostálgicos y cinestas, aceptando resignadamente y asumiendo con dolor que nunca más poseerán escala B2C masiva masiva mundial general de retail global en la vida.", "Ser banco", "Morir rápido"], a: 1 },
    { q: "La firma nipona colosal fue catalogada severamente tajantemente duramente inflexiblemente por los auditores internacionales fríos por su inmensa y colosal gigantesca e insondable absoluta nula o pasiva Carencia Total de 'Capacidades Dinámicas', indicando en castellano estratégico que un ente que falla aquí denota patológicamente la rotunda inoperancia biológico-directiva a nivel de ADN basal elemental primitivo basal original que la inutiliza y frena forzadamente de cuajo vital de fábrica estáticamente paralizada y con artrosis para:", options: ["Poder fondear pasivos exógenos estáticos perennes pasivos locales con bancos regionales y centrales amigables sumisos inactivos cómplices mudos y pasados lejanos laxos y burocráticos pasivos inofensivos adormilados siempre y no exigir control ni revisión general externa ni pública B2B ni B2C alguna vez obligatoria para accionariado preferente pasivo general y común internacional", "Poseer el músculo organizativo cultural institucional biológico genético directivo ágil y enérgico, sumado con la alerta y radar paranoico perpetuo y percepción sensible elástica vibrante de antenas tácticas y orgánicas sistémicas vivas finas sutiles que logre advertir captar o reconfigurar agresivamente, mutar biológicamente drástica frenéticamente la maquinaria de recursos del capital o de la patente interna del organigrama ágil flexible veloz mutante y rotundo pivotante en el acto veloz frente a inminentes, temibles, y letales mortales oscilaciones colosales oscuras o cataclismos disruptivos y tsunamis furiosos de Sillicon Valley implacables radicales y despiadados de olas aniquiladoras de innovación pura digital y feroz.", "No operar patentes caducadas antiguas analógicas", "Saber contabilidad de costos hundidos a NIIF"], a: 1 },
    { q: "Señalando un hipotético brillante movimiento alterno de matriz pura teórica F.A. (Fortalezas propias analógicas apalancadas y mezcladas salvajemente agresivamente y defensivamente audazmente híbrida para batir disipar absorber o licuar o combatir y neutralizar Amenazas exógenas puras digitales veloces y mortíferas y voraces externas) omitido insulsamente cegados por su arrogancia y ombliguismo clásico purista, podría haber brillado fulgurantemente siendo en un tiempo primigenio germinal táctico ideal utópico original previo a la masacre total del cisne negro estrepitoso:", options: ["Pactar con lobistas proteccionistas leyes ONU de plástico local", "Pivotar agresiva y humildemente la IP patentada secreta óptica excelsa licenciando y vendiéndoles inyectando co-brandizando sus insignias famosas prestigiosas a las propias nuevas cámaras mediocres pioneras de los móviles gigantes competidores colosales emergentes como marca y tecnología co-brandeada VIP incrustada, subiéndose ágil e inteligente de parásito astuto y simbionte perfecto VIP a la misma masiva destructiva ola gigante del software avasallador devorador como un proveedor estratégico ineludible irremplazable carísimo escaso central y glorioso rey astuto del mercado híbrido.", "Pelear comprando startups tontas sin IA", "Nada"], a: 1 },
    { q: "Desde su atalaya central el CFO paralizado y embriagado y anclado a excusas temporales inútiles e inerciales y sesgos cognitivos absurdos y suicidas engañosos del declive del imperio de Luminar, en sus reuniones trimestrales cínicas contablemente sostenía ilusamente y pasivamente letal encadenado suicida el timón hasta ir al fondo del foso general hundidos asfixiados en llantos contablemente sin apelo bajo una postura irracional de libro inútil teórica y trampa ciega general del balance y caja fúnebre zombi al:", options: ["Mantener pasivo intencional engañoso en balance con revaluaciones inflacionistas exógenas macro monetarias ficticias transnacionales de tasa cruzadas del mercado forex secundario ciego dudoso opaco negro oscuro legal ambiguo transaccional de SWIFTs en b, engañando con caja negra general", "Rehusarse cobarde tenaz testaruda tozudamente ciega a reconocer sincera dolorosamente y liquidar las gigantescas enormes mortales y dolorosas astronómicamente paralizantes Pérdidas gigantes y directas causadas puramente por depreciación natural aplastante de todas sus miles de megacentrales físicas industriales asiáticas gigantes productoras a máxima asfixia capacidad diaria operante en negativo y preferiendo devorar con hemorragia el propio valioso oxígeno del capital residual efectivo líquido oxigenado de tesorería del holding completo vivo para no reportar en la asamblea quebrado el pasivo hundido intocable doloroso contundentemente y sangrar en masa suicida zombificada sin cesar la vena aorta del efectivo rey de caja y flujo libre operativo constante B2B a cero neto muerto perenne infértil.", "Eximir pagos impositivos locales aduaneros a fábricas", "No liquidar pasivo contable diferido pasivo fiscal contable deducible"], a: 1 },
    { q: "Asumiendo que Harvard asigne y ponga en control forzado agresivo e intrusivo intervencionista de crisis y terapia médica corporativa de shock ruda y traumática violenta dolorosa un nuevo genio despiadado CEO táctico especialista frío y duro calculador al mando de la asediada arca y la junta sangrante agonizante herida moribunda, la única misión primigenia fundacional basal mandatoria y orden inmediata perentoria y prioritaria número cero o primera orden fáctica vital ejecutiva brutal sangrienta ineludible urgente vital incuestionable a realizar en su primer lunes a primera hora mañana con pulso firme frío inalterable implacable es estrictamente y sin paliativos emocionales inútiles en este caso forense general:", options: ["Comprar startups zombis europeas sin tracción P2P B2C B2B muertas pasivas estáticas y caras para intentar de modo fútil apalancar el 'Goodwill' o fondo de comercio en balance y engañar inversores pasivos opacos distraídos despistados optimistas ignorantes y ciegos novatos ilusos transnacionales globales retail.", "Aplicar torniquete hemorrágico bestial violento. Ejecutar la cirugía brutal corporativa pesada y drástica destructora de cortar y amputar toda la hemorragia mortal paralizante colosal de flujo de caja 'Cash Burn' pasivo y estático liquidando de raíz quemando deshaciendo despidiendo asumiendo y parando todas las operaciones redundantes, fábricas e infraestructuras secundarias o en declive muertas zombis cueste las multas indemnizatorias masivas laborales o locales masivas letales y punitivas que cuesten, asumiendo dolor fúnebre con tal y de única razón estricta heroica central y urgente imperativa extrema pura sagaz ruda incondicional férrea brutal de salvar y fondear financieramente oxigenada a salvo blindada fuertemente resguardada protegida blindada la minúscula y pírrica y pequeñita estricta línea de operaciones que contablemente sea el núcleo core duro duro y rentable estático asertivo marginal e inelástico elitista duro y resistente firme rocoso y vivo latente productivo que sobreviva temporalmente sin chupar pasajes externos pasivos de la muerte del resto ciego de filiales fallidas del pulpo inútil ahogado herido muerto corporativo central y desangrándose.", "Ir de vacaciones de equipo B2B motivacionales offsite de grupo directivo ejecutivo corporativo inútil ciego sordo al extranjero remoto paradisíaco general transaccional asiático lejano asiático caribeño.", "Cambiar logotipo general"], a: 1 },
    { q: "Focalizando el diagnóstico frío analítico puro certero metódico de 'La guerra pura frontal y la disrupción tecnológica asimétrica y no lineal paralela del sector moderno fluido B2C universal digitalizado ubicuo ágil genérico planetario global' analizado bajo los implacables duros crudos prismas y grillas frías analíticas cuadriculadas metodológicas empíricas académicas teóricas probadas comprobadas indiscutibles e irrebatibles crudas del análisis estructural férreo de las 5 fuerzas genéricas de Porter, podemos decantar diagnosticar evaluar e hipotetizar con plena evidencia contundente pesada demostrada e incuestionable seguridad asertiva fáctica técnica operativa y real contundente empírica general indiscutida definitiva del colapso que las temibles monstruosas empresas ágiles nativas corporativas emergentes masivas disruptivas tecnológicas intrusas de Sillicon Valley que invadieron el panorama y lo dominaron feroz aniquilando a la vieja escuela operaban intrínseca biológica genéticamente e implacablemente desde una categorización o base y posicionamiento sectorial matriz de origen base de vector operativo general táctico y estructural absoluto total frontal o asimétrico radical desde una postura teórica o flanco de:", options: ["Nuevos Entrantes torpes simples y pasivos B2B lentos que clonaron plásticamente modelos japoneses mediocres copiados idénticos calcados sin distinción pero subsidiados por un país y capital chino asiático transnacional B2C general genérico opaco", "Las startups o firmas modernas colosales digitales no atacaron frontal como un simple Entrante Novato Directo torpe fabricando iguales o mejores o clásicos engranajes de plata fotográficos pesados de museo artesanal elitista nostálgico pasivo o antiguo pesado, sino que fungieron avasallaron borraron derribaron y arrasaron universal y aplastantemente fáctica absoluta contundentemente a modo monstruoso abrumador total como Inventores creadores precursores masivos ubicuos puros y nativos hiper potentes agigantados tecnológicos ubicuos absolutos de un PRODUCTO 100% TOTALMENTE SUSTITUTO PERFECTO MASIVO asimétrico, y que desde esa letal esquina impensada asimétrica ciega innovadora tecnológica barata digital e hiper-conveniente destructiva mortal voraz radical eliminatoria volvieron en cenizas al instante redundante fúnebre zombi al sector analógico borrándolo y evaporando por omisión general absoluta pasiva en sí y extirpando la necesidad base original matriz raíz ontológica primaria primitiva de las sociedades globales masa universales y fluidas modernas masivas ansiosas globales actuales planetarias de siquiera remotamente desear B2C adquirirlo, comprarlo o tan solo tolerarlo de forma nostálgica u honrosa al antiguo producto o chasis original anticuado pesado caro aburrido pasivo general zombi", "Eran proveedores encubiertos infiltrados paralelos pasivos B2B", "Eran los mismos nipones"], a: 1 },
    { q: "El 'Axioma, Extracto, Cita o Takeaway Brutal Final' plasmado dramática fúnebremente cruda visceral pesimista y lapidariamente como colofón epitafio al cierre absoluto del caso demuestra y afirma ratifica comprueba empírica lógicamente irrefutable e incontrastablemente en análisis B2C global estratégico tecnológico profundo corporativo directivo frío y rudo moderno y brutalmente certero que sin anestesia emocional o compasiva corporativa pasiva analógica alguna, se llega a la cruel aseveración final contundente pragmática objetiva realista general global de que fatalmente ineludiblemente siempre en negocios:", options: ["El hardware gana por materiales exóticos raros insuperables estables duros férreos macizos fuertes caros exclusivos premium elitistas de oro físico", "Todo y el inmenso y glorioso supremo y absoluto inigualado inmaculado excelso esfuerzo puro colosal sudoroso y el talento titánico artesanal virtuoso manual perfeccionista romántico nostálgico milimétrico pulido noble y brillante innegable superlativo exótico puro en la construcción e ingeniería física B2C del hardware pesado mecánico más perfecto impecable sólido macizo fuerte pulido majestuoso sublime impoluto reluciente histórico e indestructible y glorioso del planeta tierra global queda irremediablemente aniquilado fulminado aniquilado evaporado inutilizado caducado y su valor mercantil contable B2B o B2C financiero o sentimental pasivo corporativo orgánico se pulveriza se calcina se derriba y se desploma irremediablemente llanamente a base a CERO ($0) CERO NETO neto frío redondo crudo e inútil en un milisegundo apenas un intangible algoritmo ágil ubicuo o pieza de software genialmente codificada innovadora etérea barata en red conectada ubicua conveniente fluida hiper potente universal hace redundante prescindible olvidable y ridículamente innecesaria social operativa logísticamente e instantáneamente su primigenia central matriz fundacional biológica antigua y obsoleta Función o Valor de Uso Original en la mente acelerada cambiante frívola móvil ubicua líquida ansiosa universal práctica fluida y moderna hiper-conectada voraz consumista de red de las masas societales globales masivas y anónimas generalistas veloces mundiales de retail o B2C.", "PESTEL no hace nada", "VRIO es inútil siempre"], a: 1 }
  ]
};
